# Generated by Django 3.2 on 2022-02-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_rename_products_mark_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ('-id',)},
        ),
    ]
