# Generated by Django 3.2 on 2021-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20211228_0727'),
        ('order', '0003_auto_20211216_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders_p', to='product.Product'),
        ),
    ]
