# Generated by Django 3.2 on 2021-12-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20211228_0727'),
        ('order', '0004_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(related_name='prders_c', to='product.Category'),
        ),
    ]
