# Generated by Django 3.2 on 2022-01-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='categories',
        ),
    ]
