# Generated by Django 3.2 on 2022-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
