# Generated by Django 3.2 on 2022-01-23 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_refundordersrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundordersrequest',
            name='Confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundordersrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
