# Generated by Django 3.2 on 2022-02-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
