# Generated by Django 3.2 on 2022-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total_c_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='c_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
