# Generated by Django 3.2 on 2022-03-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
