# Generated by Django 3.2 on 2021-12-13 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=4)),
            ],
        ),
    ]
