# Generated by Django 3.2 on 2022-01-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_userotp_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userotp',
            options={'ordering': ('-id',)},
        ),
    ]
