# Generated by Django 3.2 on 2022-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_userotp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
