# Generated by Django 3.2 on 2022-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_alter_userotp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
