# Generated by Django 3.2 on 2022-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_userotp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='email',
        ),
        migrations.AlterField(
            model_name='userotp',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
