# Generated by Django 3.2 on 2021-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=150, null=True)),
                ('graduate', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('doctorDescreption', models.TextField(blank=True, null=True)),
                ('doctorId', models.CharField(blank=True, max_length=100, null=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
