# Generated by Django 3.2 on 2021-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctorDescreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
