# Generated by Django 3.2 on 2021-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211216_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
