# Generated by Django 3.2 on 2022-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Incubation_license',
            field=models.ImageField(blank=True, null=True, upload_to='mojavezha/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='mojavezha/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='other',
            field=models.ImageField(blank=True, null=True, upload_to='mojavezha/%Y/%m/'),
        ),
    ]
