# Generated by Django 3.2 on 2022-02-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220222_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Incubation_license',
            field=models.ImageField(blank=True, default='', null=True, upload_to='mojavezha/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='other',
            field=models.ImageField(blank=True, default='', null=True, upload_to='mojavezha/%Y/%m/'),
        ),
    ]
