# Generated by Django 3.2 on 2021-12-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
