# Generated by Django 3.2 on 2021-12-14 07:31

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211213_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='products/thumbnails/%Y/%m/'),
        ),
    ]
