# Generated by Django 3.2 on 2021-12-14 15:20

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211214_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='like',
            new_name='like_count',
        ),
        migrations.AddField(
            model_name='product',
            name='ilked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_thumbnail_path),
        ),
    ]
