# Generated by Django 3.2 on 2021-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
