# Generated by Django 3.2 on 2021-12-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_likeproduct_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeproduct',
            old_name='owner',
            new_name='user',
        ),
    ]
