# Generated by Django 3.2 on 2021-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_owner_likeproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeproduct',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
