# Generated by Django 3.2 on 2021-12-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_likeproduct_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
    ]
