# Generated by Django 3.2 on 2021-12-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
