# Generated by Django 3.2 on 2021-12-25 21:19

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_pictest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicTest',
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path),
        ),
    ]
