# Generated by Django 3.2 on 2022-01-03 13:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20211228_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descreption',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
