# Generated by Django 3.2 on 2022-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after_discount',
            field=models.BigIntegerField(default=0),
        ),
    ]
