# Generated by Django 3.2 on 2022-01-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_price_after_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
    ]
