# Generated by Django 3.2 on 2022-01-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
        migrations.DeleteModel(
            name='LikeProduct',
        ),
    ]
