# Generated by Django 3.2 on 2022-01-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_pdf_file'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(related_name='pdiscount', to='product.Product'),
        ),
    ]
