# Generated by Django 3.2 on 2022-01-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discount_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='product',
            new_name='products',
        ),
    ]
