# Generated by Django 3.2 on 2022-01-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_price_after_discount'),
        ('discount', '0003_rename_product_discount_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='products',
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdiscount', to='product.product'),
            preserve_default=False,
        ),
    ]
