# Generated by Django 3.2 on 2022-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20220112_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
