# Generated by Django 3.2 on 2022-01-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_auto_20220112_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('-created_at',)},
        ),
    ]
