# Generated by Django 3.2 on 2022-01-28 10:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='news/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
