# Generated by Django 3.2 on 2022-01-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220128_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/'),
        ),
    ]
