# Generated by Django 3.2 on 2022-02-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_title_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',)},
        ),
    ]
