# Generated by Django 3.2 on 2021-12-18 09:07

from django.db import migrations, models
import django.db.models.deletion
import threeD.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_product_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=threeD.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=threeD.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=threeD.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=threeD.models.upload_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=threeD.models.upload_image_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=threeD.models.upload_image_path)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='product.product')),
            ],
        ),
    ]
