# Generated by Django 3.2 on 2022-01-28 07:23

from django.db import migrations, models
import threeD.models


class Migration(migrations.Migration):

    dependencies = [
        ('threeD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threed',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=threeD.models.uip2),
        ),
    ]
