# Generated by Django 3.2 on 2021-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threed',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image16',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image17',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image21',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image22',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image23',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image24',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image25',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image26',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image27',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image28',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image29',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image30',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='threed',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='3D/%Y/%m/'),
        ),
    ]
