# Generated by Django 3.2 on 2022-01-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_price_after_discount'),
        ('threeD', '0004_alter_threed_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threed',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='product.product'),
        ),
    ]
